# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/DRLSetListFM.xcworkspace -scheme DRLSetListFM-Example -sdk iphonesimulator -destination 'platform=iOS Simulator, id=77520D28-A1AA-42CB-BE19-5D37D76D3E86, OS=11.4, name=iPhone 5s' build | xcpretty -c --color
