//
// SFMartistmbidAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMartistMbidAPI {
    /**
     .

     - parameter mbid: (path) a Musicbrainz MBID, e.g. 0bfba3d3-6a04-4779-bb0a-df07df5b0558 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmArtistMbidGetArtist(mbid: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmArtistMbidGetArtistWithRequestBuilder(mbid: mbid).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     .
     - GET /1.0/artist/{mbid}

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter mbid: (path) a Musicbrainz MBID, e.g. 0bfba3d3-6a04-4779-bb0a-df07df5b0558 

     - returns: RequestBuilder<Void> 
     */
    open class func sfmArtistMbidGetArtistWithRequestBuilder(mbid: String) -> RequestBuilder<Void> {
        var path = "/1.0/artist/{mbid}"
        let mbidPreEscape = "\(mbid)"
        let mbidPostEscape = mbidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{mbid}", with: mbidPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
