//
// SFMartistmbidsetlistsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMartistMbidSetlistsAPI {
    /**
     .

     - parameter mbid: (path) the Musicbrainz MBID of the artist 
     - parameter p: (query) the number of the result page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmArtistMbidSetlistsGetArtistSetlists(mbid: String, p: Int? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmArtistMbidSetlistsGetArtistSetlistsWithRequestBuilder(mbid: mbid, p: p).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     .
     - GET /1.0/artist/{mbid}/setlists

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter mbid: (path) the Musicbrainz MBID of the artist 
     - parameter p: (query) the number of the result page (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sfmArtistMbidSetlistsGetArtistSetlistsWithRequestBuilder(mbid: String, p: Int? = nil) -> RequestBuilder<Void> {
        var path = "/1.0/artist/{mbid}/setlists"
        let mbidPreEscape = "\(mbid)"
        let mbidPostEscape = mbidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{mbid}", with: mbidPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "p": p?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
