//
// SFMcitygeoIdAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMcityGeoIdAPI {
    /**
     Get a city by its unique geoId.

     - parameter geoId: (path) the city&#x27;s geoId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmCityGeoIdGetCity(geoId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmCityGeoIdGetCityWithRequestBuilder(geoId: geoId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Get a city by its unique geoId.
     - GET /1.0/city/{geoId}

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter geoId: (path) the city&#x27;s geoId 

     - returns: RequestBuilder<Void> 
     */
    open class func sfmCityGeoIdGetCityWithRequestBuilder(geoId: String) -> RequestBuilder<Void> {
        var path = "/1.0/city/{geoId}"
        let geoIdPreEscape = "\(geoId)"
        let geoIdPostEscape = geoIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{geoId}", with: geoIdPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
