//
// SFMsearchcitiesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMsearchCitiesAPI {
    /**
     Search for a city.

     - parameter country: (query) the city&#x27;s country (optional)
     - parameter name: (query) name of the city (optional)
     - parameter p: (query) the number of the result page you&#x27;d like to have (optional)
     - parameter state: (query) state the city lies in (optional)
     - parameter stateCode: (query) state code the city lies in (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmSearchCitiesGetCities(country: String? = nil, name: String? = nil, p: Int? = nil, state: String? = nil, stateCode: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmSearchCitiesGetCitiesWithRequestBuilder(country: country, name: name, p: p, state: state, stateCode: stateCode).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Search for a city.
     - GET /1.0/search/cities

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter country: (query) the city&#x27;s country (optional)
     - parameter name: (query) name of the city (optional)
     - parameter p: (query) the number of the result page you&#x27;d like to have (optional)
     - parameter state: (query) state the city lies in (optional)
     - parameter stateCode: (query) state code the city lies in (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sfmSearchCitiesGetCitiesWithRequestBuilder(country: String? = nil, name: String? = nil, p: Int? = nil, state: String? = nil, stateCode: String? = nil) -> RequestBuilder<Void> {
        let path = "/1.0/search/cities"
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "country": country, 
                        "name": name, 
                        "p": p?.encodeToJSON(), 
                        "state": state, 
                        "stateCode": stateCode
        ])


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
