//
// SFMsetlistsetlistIdAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMsetlistBySetlistIdAPI {
    /**
     .

     - parameter setlistId: (path) the setlist id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmSetlistSetlistIdGetSetlist(setlistId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmSetlistSetlistIdGetSetlistWithRequestBuilder(setlistId: setlistId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     .
     - GET /1.0/setlist/{setlistId}

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter setlistId: (path) the setlist id 

     - returns: RequestBuilder<Void> 
     */
    open class func sfmSetlistSetlistIdGetSetlistWithRequestBuilder(setlistId: String) -> RequestBuilder<Void> {
        var path = "/1.0/setlist/{setlistId}"
        let setlistIdPreEscape = "\(setlistId)"
        let setlistIdPostEscape = setlistIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{setlistId}", with: setlistIdPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
