//
// SFMsetlistversionversionIdAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMsetlistVersionByVersionIdAPI {
    /**
     .

     - parameter versionId: (path) the version id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmSetlistVersionVersionIdGetSetlistVersionT(versionId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmSetlistVersionVersionIdGetSetlistVersionTWithRequestBuilder(versionId: versionId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     .
     - GET /1.0/setlist/version/{versionId}

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter versionId: (path) the version id 

     - returns: RequestBuilder<Void> 
     */
    open class func sfmSetlistVersionVersionIdGetSetlistVersionTWithRequestBuilder(versionId: String) -> RequestBuilder<Void> {
        var path = "/1.0/setlist/version/{versionId}"
        let versionIdPreEscape = "\(versionId)"
        let versionIdPostEscape = versionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{versionId}", with: versionIdPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
