//
// SFMuseruserIdAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMuserByUserIdAPI {
    /**
     Get a user by userId.

     - parameter userId: (path) the user&#x27;s userId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmUserUserIdGetUser(userId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmUserUserIdGetUserWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Get a user by userId.
     - GET /1.0/user/{userId}

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter userId: (path) the user&#x27;s userId 

     - returns: RequestBuilder<Void> 
     */
    open class func sfmUserUserIdGetUserWithRequestBuilder(userId: String) -> RequestBuilder<Void> {
        var path = "/1.0/user/{userId}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
