//
// SFMvenuevenueIdsetlistsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SFMvenueByVenueIdsetlistsAPI {
    /**
     .

     - parameter venueId: (path) the id of the venue 
     - parameter p: (query) the number of the result page (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sfmVenueVenueIdSetlistsGetVenueSetlists(venueId: String, p: Int? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sfmVenueVenueIdSetlistsGetVenueSetlistsWithRequestBuilder(venueId: venueId, p: p).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     .
     - GET /1.0/venue/{venueId}/setlists

     - API Key:
       - type: apiKey X-API-KEY 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example=""}]
     - parameter venueId: (path) the id of the venue 
     - parameter p: (query) the number of the result page (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sfmVenueVenueIdSetlistsGetVenueSetlistsWithRequestBuilder(venueId: String, p: Int? = nil) -> RequestBuilder<Void> {
        var path = "/1.0/venue/{venueId}/setlists"
        let venueIdPreEscape = "\(venueId)"
        let venueIdPostEscape = venueIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{venueId}", with: venueIdPostEscape, options: .literal, range: nil)
        let URLString = DRLSetlistFM.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "p": p?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<Void>.Type = DRLSetlistFM.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
